Ai add pundit
aizatibraimova/industrial-auth-1 pull request #2
Opened 2024-07-17 16:55 UTC by aizatibraimova

2024-07-19 20:03 UTC, aborov requested changes
It's a great start, but needs some adjustments. See my findings below.

2024-07-19 20:03 UTC, aborov commented on app/controllers/application_controller.rb
> +
Great job setting up application-level "security by default" turning on Pundit and setting `rescue` and `after_action`

2024-07-19 20:03 UTC, aborov commented on app/views/comments/show.html.erb
> +
You might want to revise your comments view as currently I can see icons to edit and delete comments, even for the ones made by other users (the good thing when you click it it actually won't allow the action and you get the right alert, but you're not supposed to see those icons in the first place)

2024-07-19 20:03 UTC, aborov commented on app/controllers/users_controller.rb
You might want to revise the policy on users (from the `users_controller` all the way down to the `show` view) as currently I can see photos from private users and their comments under photos

2024-07-19 20:03 UTC, aborov commented on app/policies/photo_policy.rb
> +  #   see it
You might want to specify cases when a user is trying to edit or delete their own photos. Currently they can't.

2024-07-22 03:08 UTC, ajmompr requested changes
great start; see comments

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/application_controller.rb
> +
great

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
great!

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?
great!

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/comments_controller.rb
Great start! You can refactor to be more DRY using before_action -> { authorize @comment || Comment },except: [:new, :create]. By calling this before action in your controller, you can remove each instance of authorize @comment. Same concept can be applied across your controllers

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: %i[accept destroy]
Refactor to be more DRY! replace with before_action { authorize @follow_request || FollowRequest } and see notes from your comments controller

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +    authorize @follow_request
refactor to be more DRY

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
refactor to be more DRY

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, except: %i[ index new create ]
before_action { authorize @photo || Photo }

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action :authorize_user, except: %i[ index new create ]
before_action { authorize @user || User }

2024-07-22 03:08 UTC, ajmompr commented on app/controllers/users_controller.rb
refactor to be more DRY

2024-07-22 03:08 UTC, ajmompr commented on app/policies/application_policy.rb
good job using pundit generator

2024-07-22 03:08 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == comment.author || !comment.author.private? || comment.author.followers.include?(user)
this is okay; however, we want to display all comments. If a photo is private then, we would not need this logic

2024-07-22 03:08 UTC, ajmompr commented on app/policies/comment_policy.rb
> +  class Scope < Scope
scope can just be inherited from application policy

2024-07-22 03:08 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +   def update?
Who else can update? Remember, It takes two users to exchange follows

2024-07-22 03:08 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +    user == follow_request.sender || follow_request.recipient
good

2024-07-22 03:08 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +    user == comment.author
Why are we calling comment.author in follow request policy?

2024-07-22 03:08 UTC, ajmompr commented on app/policies/photo_policy.rb
> +  #   see it
added on lines 24-33

2024-07-22 03:08 UTC, ajmompr commented on app/policies/photo_policy.rb
> +    user == photo.owner || !photo.owner.private? || photo.owner.followers.include?(user)
good

2024-07-22 03:08 UTC, ajmompr commented on app/policies/user_policy.rb
> +    true
Not quite. Should user == current_user

2024-07-22 03:08 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def update?
Do we need to give users edit and update access based on the current version of the photogram app? Also, nitpick; if you are going to use inheritance, place update? before edit?

2024-07-22 03:08 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def destroy?
Do we need to give current_user the ability to destroy user record?

2024-07-22 03:08 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
Almost, but not quite. You need to add another policy method to ensure that the photo feed is displaying properly for both public and private users

2024-07-23 01:59 UTC, aborov requested changes
that's a great progress! however, there are still some spots that call for revision. see my comments below.

2024-07-23 01:59 UTC, aborov commented on app/controllers/follow_requests_controller.rb
> +  before_action -> { authorize @follow_request || FollowRequest }, only: [:show, :edit, :update, :destroy]
Great job refactoring your controller to make your code more concise! Please double check your restrictions as it seems like a current user isn't authorized to accept pending requests.

2024-07-23 01:59 UTC, aborov commented on app/controllers/comments_controller.rb
> +  before_action -> { authorize @comment || Comment }, except: %i[new create]
Nice work refactoring comments! It is indeed more consice now.

2024-07-23 01:59 UTC, aborov commented on app/controllers/users_controller.rb
> +  before_action -> { authorize @user || User }
Awesome work using concise authorization for users! Now you can actually take out almost all of your actions in this controller!

2024-07-23 01:59 UTC, aborov commented on app/policies/comment_policy.rb
you should be good to take many of these actions out

2024-07-23 01:59 UTC, aborov commented on app/policies/follow_request_policy.rb
> +    true
good!

2024-07-23 01:59 UTC, aborov commented on app/policies/follow_request_policy.rb
> +    user == follow_request.sender || user == follow_request.recipient
also you can just say:
```ruby
def destroy?
  update?
end
```

2024-07-23 01:59 UTC, aborov commented on app/policies/follow_request_policy.rb
> +    user == follow_request.recipient
I think you don't need it

2024-07-23 01:59 UTC, aborov commented on app/policies/photo_policy.rb
>    end
You might want to revise it: currently, when a user is trying to update their own photo, they are not authorized for that

2024-07-23 01:59 UTC, aborov commented on app/policies/photo_policy.rb
>      user == photo.owner
this can be simplified to 
```ruby
def destroy?
  update?
end
```

2024-07-23 01:59 UTC, aborov commented on app/policies/user_policy.rb
`discover` currently doesn't work, so you might want to find out what's broken.
Also, you currently can't access profile pages for any private users at all.

2024-07-23 01:59 UTC, aborov commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
awesome!

2024-07-23 20:21 UTC, aborov approved these changes
great job, Aizat!

2024-07-23 20:21 UTC, aborov commented on app/policies/user_policy.rb
> +    update?
great use of inheritance!

2024-07-23 20:21 UTC, aborov commented on app/views/comments/_comment.html.erb
> +    <% if comment.author== current_user %>
nice job hiding editing buttons from users that don't own this comment!

2024-07-23 20:21 UTC, aborov commented on app/views/users/_user.html.erb
> +        <% if @user != current_user %>
nice way to hide pending requests for users who are looking at the profile that's not their own!

2024-07-24 14:01 UTC, ajmompr approved these changes
A lot of the work that you are doing is redundant because you have added the before_action { authorize ...} in your controllers. Be sure to stay consistent when adding your authorizations

2024-07-24 14:01 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +    @follow_requests = policy_scope(FollowRequest)
redundant if you are calling before_action! But okay

2024-07-24 14:01 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant if calling before_action but okay

2024-07-24 14:31 UTC, merged